import * as THREE from 'three';

// ── A baked COLOR_0 cannot be tinted ─────────────────────────────────────────────────────────────
//
// GLB Studio's `bakeVertexColors` folds a model's base-colour TEXTURE into per-vertex colours and
// then drops the texture. That is a deliberate, good trade — it is how a Meshy download of several
// megabytes becomes a file a phone can load. But it puts the artwork's HUE into the geometry, and
// three.js MULTIPLIES the material colour by the vertex colour. So for a recolourable element the
// two cancel out:
//
//   fondant heart   COLOR_0 mean #bd0101, saturation 0.997   ask for cream → renders RED
//                                                            ask for blue  → renders nearly BLACK
//
// Reported as "I have set color-changeable but I can't change the colour in the designer". Nothing
// was wrong with the colour path: the swatch wrote the colour, the renderer applied it, and the red
// in the file ate it. Measured across the catalogue on 2026-09-22: 8 of the 31 colour-changeable
// GLBs carry COLOR_0, and every one of them is generated by Meshy, so this recurs for each new one.
//
// ⚠️ THE HUE GOES, THE SHADING STAYS. Dropping the attribute altogether would flatten the model —
// COLOR_0 also carries the light and dark of the form (Shell Fan ranges 0.42–0.99), and that is what
// makes a piped shell read as piped. Converting to LUMINANCE keeps every one of those relationships
// and removes only the colour, so the tint arrives clean over the baked shading.
//
// ⚠️ AND IT MUST BE NORMALISED, OR IT IS A DIMMER. The heart's baked luminance is 0.11–0.23. Grey at
// those values multiplies a chosen colour down to a quarter of itself, which trades a wrong hue for
// a muddy one. Scaling so the brightest vertex is 1.0 makes the attribute a shading ramp, which is
// the only thing it should have been.
//
// ⚠️ ONLY FOR ELEMENTS THAT SAY THEY ARE RECOLOURABLE (`allowed_actions.color`). A model that is NOT
// colour-changeable is showing the colours it was authored with, and those are correct — a unicorn
// eye is black because eyes are black, a chocolate bar is brown because chocolate is brown. Take the
// hue out of one of those and it renders in whatever `default_color` happens to say. The flag is the
// element's own statement about which it is; nothing here branches on a name or a type.
//
// No re-upload: this runs on the loader's CLONE, so the file on the CDN is untouched and every saved
// design keeps pointing at the same asset.

const R = 0.2126, G = 0.7152, B = 0.0722;

/**
 * The grey each vertex becomes: relative luminance, scaled so the brightest vertex is 1.0.
 *
 * Exported for the test, and because the arithmetic is the whole decision — `peak` is passed in
 * rather than computed per attribute so that a model whose parts are separate meshes keeps the
 * relationship BETWEEN them (one dark part and one light part stay dark and light).
 *
 * @param {ArrayLike<number>} rgb  interleaved colour components, already 0–1
 * @param {number} itemSize        3 (VEC3) or 4 (VEC4 — alpha is carried through untouched)
 * @param {number} peak            the brightest luminance to normalise against; ≤0 → no scaling
 */
export function greysFromColours(rgb, itemSize, peak) {
  const out = new Float32Array(rgb.length);
  const k = peak > 0 ? 1 / peak : 1;
  for (let i = 0; i < rgb.length; i += itemSize) {
    const g = Math.min(1, (R * rgb[i] + G * rgb[i + 1] + B * rgb[i + 2]) * k);
    out[i] = g; out[i + 1] = g; out[i + 2] = g;
    if (itemSize === 4) out[i + 3] = rgb[i + 3];
  }
  return out;
}

/** The brightest luminance in a set of 0–1 colour components. */
export function peakLuminance(rgb, itemSize) {
  let peak = 0;
  for (let i = 0; i < rgb.length; i += itemSize) {
    const L = R * rgb[i] + G * rgb[i + 1] + B * rgb[i + 2];
    if (L > peak) peak = L;
  }
  return peak;
}

/** Colour components as plain 0–1 floats, whatever the attribute's storage type. */
function componentsOf(attr) {
  const { array, normalized, itemSize } = attr;
  if (!normalized) return { rgb: array, itemSize };
  const out = new Float32Array(array.length);
  for (let i = 0; i < array.length; i++) out[i] = THREE.MathUtils.denormalize(array[i], array);
  return { rgb: out, itemSize };
}

/**
 * Take the hue out of every baked vertex colour in a loaded model, keeping its shading.
 *
 * Mutates the object graph it is given — call it on the LOADER'S CLONE, never on the cached scene,
 * or every instance of the element on the cake shares the result. Geometry is cloned per mesh here
 * for the same reason: `scene.clone(true)` shares geometry by reference.
 *
 * Returns the number of meshes changed, so a caller (or a harness) can tell "nothing to do" from
 * "done" without inspecting the scene.
 */
export function neutraliseBakedColour(root) {
  const meshes = [];
  root.traverse(obj => { if (obj.isMesh && obj.geometry?.getAttribute('color')) meshes.push(obj); });
  if (!meshes.length) return 0;

  // One peak for the whole model — see greysFromColours.
  let peak = 0;
  const reads = meshes.map(m => {
    const { rgb, itemSize } = componentsOf(m.geometry.getAttribute('color'));
    peak = Math.max(peak, peakLuminance(rgb, itemSize));
    return { rgb, itemSize };
  });

  meshes.forEach((mesh, i) => {
    const { rgb, itemSize } = reads[i];
    mesh.geometry = mesh.geometry.clone();
    mesh.geometry.setAttribute('color', new THREE.BufferAttribute(greysFromColours(rgb, itemSize, peak), itemSize));
  });
  return meshes.length;
}
