// ── Which HDRI every scene lights itself with ────────────────────────────────────────────────────
//
// Its own module, not a corner of CakeCanvas, because FIVE canvases need the answer and four of them
// are previews that CakeCanvas itself renders — reaching back into it would be a cycle.
//
// ── Why this exists at all ──────────────────────────────────────────────────────────────────────
// TopperPreview, PipingPreview, PatternBuilderCanvas and CreamPenCalibrator each hardcoded
// `preset="apartment"`. drei resolves that to a 1.4 MB HDR on raw.githubusercontent.com — so every
// one of those previews fetched, from a public CDN, the very file we self-host to avoid it. The CDN
// is the one SafeEnvironment's own comment calls flaky and rate-limited, and the request only got
// through because the CSP is still report-only; turning CSP_ENFORCE on would have broken all four
// at once, silently, since SafeEnvironment catches the throw and renders nothing. The only symptom
// would have been previews looking slightly flat.
//
// Found 2026-08-17 in a storefront console, while chasing a different bug entirely.
//
// The host supplies the assets base (an env var, dev/prod-specific); only this PATH is a constant.
// A module-level singleton because the value has to cross the R3F <Canvas> boundary, and threading
// it as a prop through six components was how four of them came to be missing it.

// 256×128, 96 KB. The 1k original is 1.4 MB and loads before the cake is on screen, which on mobile
// data was most of the wait — and it bought almost nothing, since three.js convolves the map for
// roughness anyway and a cake is fondant rather than chrome. All four sizes are in R2, so changing
// the look is THIS LINE: 512 is the step back if gold leaf or a chocolate drip ever reads too soft.
// Generated by spattoo-api/scripts/downsample-hdr.mjs.
// ⚠️ AND THIS IS THE FIRST THING TO TRY FOR THE GOLD-TOPPER GLARE — the two suspects are both here.
//
// Lebombo is an OUTDOOR map: most of its sphere is open sky, which is a large, bright, featureless
// field. A metal has no colour of its own and shows nothing but the reflection, so an open sky gives
// it a sheet of white to mirror — which is what glare is. An INDOOR map (a studio or a room, with a
// window as a defined source and darker surrounds) gives the bands of light and shade that read as
// gold. The parameter search is exhausted: rotation, roughness and the finish's own envIntensity were
// each swept on the real cake and each is already at its best value while the glare remains, so what
// is left is the map's content.
//
// ⚠️ RESOLUTION IS NOT THE CAUSE — MEASURED AND REFUTED. The note above guessed that 256×128 was too
// coarse for a mirror. It is not: on the real cake the relative contrast of the gold lettering reads
// 0.360 at 256, 0.357 at 512 and 0.391 at 1k, so 512 is indistinguishable from 256 and 1k buys 8%
// for fifteen times the bytes. Keep 256. The guess was reasonable and wrong, which is the whole
// reason it was measured before being shipped.
//
// ⚠️ WHAT IS LEFT IS THE MAP'S CONTENT, AND THAT IS CONFIRMED. Swapping in an INDOOR map, same cake
// same metric, moves both numbers the right way at once:
//
//     lebombo (outdoor, ships today)   mean 187   relative contrast 0.346
//     studio_small_09 (indoor)         mean 133   relative contrast 0.476   <- 29% less washed out, 38% more banding
//     brown_photostudio_02             mean 153   0.386
//     photo_studio_01                  mean 170   0.259
//     empty_warehouse_01               mean 177   0.202
//
// An open sky is one large featureless bright field, and a metal has no colour of its own — it shows
// the map and nothing else, so it shows a sheet of white. A studio map has defined sources with dark
// surrounds, which is what gives gold its bands.
//
// ⚠️ SWAPPING THE MAP IS NOT A ONE-LINE CHANGE, because it re-lights EVERY surface, not just metal.
// `REFERENCE_LIGHT` in `garnishMaterial.js` is a measurement of how much light this environment
// throws at a garnish, and under studio_small_09 every colour lands ~38 points dark in sRGB (grey
// 128 renders 90). Re-measure it in the same commit or every garnish ships wrong. The candidate also
// has to reach R2 first — see spattoo-api's downsample-hdr.mjs.
// ⚠️ THE STUDIO MAP WAS TRIED HERE AND REVERTED — DO NOT REACH FOR IT AGAIN WITHOUT READING THIS.
// `studio_256.hdr` genuinely fixes the gold topper (mean 187 → 133, relative contrast 0.346 → 0.476,
// and the lettering goes from illegible mid-word to readable). It is in R2 and it works. It was
// reverted anyway, because THE HDRI IS A SCENE PROPERTY AND THE PROBLEM IS ONE ELEMENT'S.
//
// Every metal in the library shares this map: faux balls, acrylic words, age numbers, gold leaf, the
// board. Dimming it to stop a FLAT letterform mirroring an open sky also took away the bright source
// that a CURVED ball needs to catch, and the faux balls went dull and matte — reported from dev the
// same afternoon. A sphere and a flat letter want opposite things from the same light, so no single
// map satisfies both, and tuning this line harder cannot fix that.
//
// ⚠️ AND THE EVIDENCE THAT JUSTIFIED THE SWAP WAS INVALID. The sweeps that concluded "no material
// -side lever exists" — rotation, roughness, envIntensity — were every one of them measured while
// the harness was rendering drei's `apartment` fallback instead of this file. A scene-wide lever was
// chosen because a local one had been ruled out on data that never described the real scene.
//
// The fix belongs on the topper's own material, or failing that on a per-material `envMap` (three.js
// lets a material override `scene.environment`), so metals can differ from each other.
const ENV_HDR_PATH = 'code/env/lebombo_256.hdr';

let _envMapUrl = null;

/**
 * cfAssetsBase  the host's assets origin; null/absent falls back to drei's preset
 * path          which HDRI under that base — defaults to the shipped one
 *
 * ⚠️ `path` EXISTS SO THE MAP CAN BE COMPARED WITHOUT EDITING THE CONSTANT. Choosing between 256,
 * 512 and an indoor map is a measurement, and a measurement that requires a source edit and a
 * rebuild between readings is one nobody repeats. `scripts/measure-topper-glare.mjs` sweeps it.
 * Production passes one argument and gets ENV_HDR_PATH, which stays the single shipped answer.
 */
export function configureEnvMap(cfAssetsBase, path = ENV_HDR_PATH) {
  _envMapUrl = cfAssetsBase ? `${String(cfAssetsBase).replace(/\/$/, '')}/${path}` : null;
}

export function envMapUrl() { return _envMapUrl; }

/**
 * The props to spread onto <SafeEnvironment>: our self-hosted map when the host configured an assets
 * base, drei's preset only when it did not.
 *
 * The fallback is deliberately kept — a local dev run with no assets base still gets lighting rather
 * than a black scene. It is a fallback, though, and was never meant to be the normal path.
 */
let _warnedFallback = false;

export function envProps(preset = 'apartment') {
  if (_envMapUrl) return { files: _envMapUrl };
  /* ⚠️ THE FALLBACK MUST ANNOUNCE ITSELF. Its silence is what made three parameter sweeps, a set of
     documented conclusions and a shipped scene-wide change all describe a scene no customer has ever
     seen: localhost quietly rendered drei's indoor `apartment` while every deployed cake rendered the
     self-hosted OUTDOOR map, and nothing said so. The fallback is still right — a cold `npm run dev`
     deserves lighting rather than a black scene — but "right" and "invisible" are different things,
     and anything MEASURING this scene has to know it is not the real one. */
  if (!_warnedFallback && typeof console !== 'undefined') {
    _warnedFallback = true;
    console.warn(
      `[spattoo/env] No assets base configured — lighting with drei's "${preset}" preset, NOT the ` +
      `shipped ${ENV_HDR_PATH}. These are DIFFERENT environments: anything judged or measured here ` +
      `does not describe what a customer sees. Call configureEnvMap(assetsBase) — dev harnesses can ` +
      `use dev/scene.js.`);
  }
  return { preset };
}
