// ── Which HDRI every scene lights itself with ────────────────────────────────────────────────────
//
// Its own module, not a corner of CakeCanvas, because FIVE canvases need the answer and four of them
// are previews that CakeCanvas itself renders — reaching back into it would be a cycle.
//
// ── Why this exists at all ──────────────────────────────────────────────────────────────────────
// TopperPreview, PipingPreview, PatternBuilderCanvas and CreamPenCalibrator each hardcoded
// `preset="apartment"`. drei resolves that to a 1.4 MB HDR on raw.githubusercontent.com — so every
// one of those previews fetched, from a public CDN, the very file we self-host to avoid it. The CDN
// is the one SafeEnvironment's own comment calls flaky and rate-limited, and the request only got
// through because the CSP is still report-only; turning CSP_ENFORCE on would have broken all four
// at once, silently, since SafeEnvironment catches the throw and renders nothing. The only symptom
// would have been previews looking slightly flat.
//
// Found 2026-08-17 in a storefront console, while chasing a different bug entirely.
//
// The host supplies the assets base (an env var, dev/prod-specific); only this PATH is a constant.
// A module-level singleton because the value has to cross the R3F <Canvas> boundary, and threading
// it as a prop through six components was how four of them came to be missing it.

// 256×128, 96 KB. The 1k original is 1.4 MB and loads before the cake is on screen, which on mobile
// data was most of the wait — and it bought almost nothing, since three.js convolves the map for
// roughness anyway and a cake is fondant rather than chrome. All four sizes are in R2, so changing
// the look is THIS LINE: 512 is the step back if gold leaf or a chocolate drip ever reads too soft.
// Generated by spattoo-api/scripts/downsample-hdr.mjs.
// ⚠️ AND THIS IS THE FIRST THING TO TRY FOR THE GOLD-TOPPER GLARE — the two suspects are both here.
//
// Lebombo is an OUTDOOR map: most of its sphere is open sky, which is a large, bright, featureless
// field. A metal has no colour of its own and shows nothing but the reflection, so an open sky gives
// it a sheet of white to mirror — which is what glare is. An INDOOR map (a studio or a room, with a
// window as a defined source and darker surrounds) gives the bands of light and shade that read as
// gold. The parameter search is exhausted: rotation, roughness and the finish's own envIntensity were
// each swept on the real cake and each is already at its best value while the glare remains, so what
// is left is the map's content.
//
// ⚠️ AND 256×128 IS VERY LOW FOR A MIRROR. It is right for fondant, which convolves it away, but a
// mirror shows the map almost directly — at this size there is little structure left TO show. The
// note below already anticipates this: 512 is the step back "if gold leaf reads too soft". All four
// sizes are in R2, so it is one line.
//
// ⚠️ MEASURE ON THE REAL MAP, NOT THE FALLBACK. `cfAssetsBase` is unset in the dev harness, so
// localhost renders drei's `apartment` preset while the deployed app renders THIS file. Every glare
// number taken so far was against `apartment` and does not describe what a customer sees. Call
// `configureEnvMap()` in the harness before sweeping anything again.
const ENV_HDR_PATH = 'code/env/lebombo_256.hdr';

let _envMapUrl = null;

export function configureEnvMap(cfAssetsBase) {
  _envMapUrl = cfAssetsBase ? `${String(cfAssetsBase).replace(/\/$/, '')}/${ENV_HDR_PATH}` : null;
}

export function envMapUrl() { return _envMapUrl; }

/**
 * The props to spread onto <SafeEnvironment>: our self-hosted map when the host configured an assets
 * base, drei's preset only when it did not.
 *
 * The fallback is deliberately kept — a local dev run with no assets base still gets lighting rather
 * than a black scene. It is a fallback, though, and was never meant to be the normal path.
 */
export function envProps(preset = 'apartment') {
  return _envMapUrl ? { files: _envMapUrl } : { preset };
}
